Check for bevy_internal imports in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -333,3 +333,25 @@ jobs:
         with:
           name: msrv
           path: msrv/
+
+  check-bevy-internal-imports-in-examples:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check for bevy_internal imports in examples
+        shell: bash
+        run: |
+          errors=""
+          for file in $(find examples -name '*.rs'); do
+              if grep -q "use bevy_internal" "$file"; then
+                  errors+="ERROR: Detected 'use bevy_internal' in $file\n"
+              fi
+          done
+          if [ -n "$errors" ]; then
+              echo "$errors"
+              echo " Avoid importing bevy_internal, it should not be used direclty"
+              echo " Fix the issue by replacing 'bevy_internal' with 'bevy'"
+              echo " Example: 'use bevy::sprite::MaterialMesh2dBundle;' instead of 'bevy_internal::sprite::MaterialMesh2dBundle;'"
+              exit 1
+          fi                  
